version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_URL}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_network

  redis:
    image: redis:latest
    container_name: redis_ecommerce
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ecommerce_network
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  mysql_data:

networks:
  ecommerce_network:
    driver: bridge